// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Contexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(BlazingShopContext))]
    [Migration("20240402090510_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", "common");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1271d99-2909-42a4-b8b8-62cde6e808d6"),
                            Icon = "bi bi-book",
                            Title = "Books",
                            Url = "books"
                        },
                        new
                        {
                            Id = new Guid("3e320d7f-c09d-49d3-96d7-5b20b8346215"),
                            Icon = "bi bi-camera",
                            Title = "Electronics",
                            Url = "electronics"
                        },
                        new
                        {
                            Id = new Guid("4802dba6-5e8d-4e23-a83d-549f1e8bf97a"),
                            Icon = "bi bi-controller",
                            Title = "Video Games",
                            Url = "video-games"
                        });
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("original_price");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products", "common");

                    b.HasData(
                        new
                        {
                            Id = new Guid("905d2de4-cce5-43b5-b927-29c650761537"),
                            CreatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3097),
                            Description = "The Hitchhiker's Guide to the Galaxy (sometimes referred to as HG2G, HHGTTG, H2G2, or tHGttG) is a comedy science fiction series created by Douglas Adams.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/b/bd/H2G2_UK_front_cover.jpg",
                            OriginalPrice = 9.99m,
                            Price = 9.99m,
                            Title = "The Hitchhiker's Guide to the Galaxy",
                            UpdatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3101)
                        },
                        new
                        {
                            Id = new Guid("8a5f332a-2088-4b25-964e-42c54fb23d09"),
                            CreatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3121),
                            Description = "Ready Player One is a 2011 science fiction novel, and the debut novel of American author Ernest Cline. The story, set in a dystopia in 2045, follows protagonist Wade Watts on his search for an Easter egg in a worldwide virtual reality game, the discovery of which would lead him to inherit the game creator's fortune.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/a/a4/Ready_Player_One_cover.jpg",
                            OriginalPrice = 7.99m,
                            Price = 7.99m,
                            Title = "Ready Player One",
                            UpdatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3122)
                        },
                        new
                        {
                            Id = new Guid("d8c1b0b4-68cd-4b93-bdcd-f653f592c3e1"),
                            CreatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3130),
                            Description = "Nineteen Eighty-Four: A Novel, often published as 1984, is a dystopian social science fiction novel by English novelist George Orwell. It was published on 8 June 1949 by Secker & Warburg as Orwell's ninth and final book completed in his lifetime.",
                            Image = "https://i.pinimg.com/originals/db/0b/0e/db0b0e8e11fb40b303c7c2583a5aea5f.jpg",
                            OriginalPrice = 6.99m,
                            Price = 6.99m,
                            Title = "Nineteen Eighty-Four",
                            UpdatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3130)
                        },
                        new
                        {
                            Id = new Guid("d1dc0494-dde8-41d5-80d5-1958d1201dec"),
                            CreatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3139),
                            Description = "The Pentax Spotmatic refers to a family of 35mm single-lens reflex cameras manufactured by the Asahi Optical Co. Ltd., later known as Pentax Corporation, between 1964 and 1976.",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/e/e9/Honeywell-Pentax-Spotmatic.jpg",
                            OriginalPrice = 166.66m,
                            Price = 166.66m,
                            Title = "Pentax Spotmatic",
                            UpdatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3139)
                        },
                        new
                        {
                            Id = new Guid("ef55828e-cb70-4f26-89af-0c6e8fd5eb44"),
                            CreatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3147),
                            Description = "The Xbox is a home video game console and the first installment in the Xbox series of video game consoles manufactured by Microsoft.",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/4/43/Xbox-console.jpg",
                            OriginalPrice = 159.99m,
                            Price = 159.99m,
                            Title = "Xbox",
                            UpdatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3147)
                        },
                        new
                        {
                            Id = new Guid("cb08880a-1906-489d-9516-25a15289418b"),
                            CreatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3180),
                            Description = "The Super Nintendo Entertainment System (SNES), also known as the Super NES or Super Nintendo, is a 16-bit home video game console developed by Nintendo that was released in 1990 in Japan and South Korea.",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/e/ee/Nintendo-Super-Famicom-Set-FL.jpg",
                            OriginalPrice = 73.74m,
                            Price = 73.74m,
                            Title = "Super Nintendo Entertainment System",
                            UpdatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3181)
                        },
                        new
                        {
                            Id = new Guid("7d438ef0-9719-4a2d-b447-e6ea7419bf42"),
                            CreatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3188),
                            Description = "Half-Life 2 is a 2004 first-person shooter game developed and published by Valve. Like the original Half-Life, it combines shooting, puzzles, and storytelling, and adds features such as vehicles and physics-based gameplay.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/2/25/Half-Life_2_cover.jpg",
                            OriginalPrice = 8.19m,
                            Price = 8.19m,
                            Title = "Half-Life 2",
                            UpdatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3188)
                        },
                        new
                        {
                            Id = new Guid("ada0c7ef-e010-4633-b091-99f68bfdd0e6"),
                            CreatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3195),
                            Description = "Diablo II is an action role-playing hack-and-slash computer video game developed by Blizzard North and published by Blizzard Entertainment in 2000 for Microsoft Windows, Classic Mac OS, and macOS.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/d/d5/Diablo_II_Coverart.png",
                            OriginalPrice = 9.99m,
                            Price = 9.99m,
                            Title = "Diablo II",
                            UpdatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3196)
                        },
                        new
                        {
                            Id = new Guid("161a87eb-c8da-48da-9654-cea51656f60d"),
                            CreatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3203),
                            Description = "Day of the Tentacle, also known as Maniac Mansion II: Day of the Tentacle, is a 1993 graphic adventure game developed and published by LucasArts. It is the sequel to the 1987 game Maniac Mansion.",
                            Image = "https://upload.wikimedia.org/wikipedia/en/7/79/Day_of_the_Tentacle_artwork.jpg",
                            OriginalPrice = 14.99m,
                            Price = 14.99m,
                            Title = "Day of the Tentacle",
                            UpdatedAt = new DateTime(2024, 4, 2, 9, 5, 10, 310, DateTimeKind.Utc).AddTicks(3203)
                        });
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "accounts");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.OwnsOne("Domain.Users.Owns.Contact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("contact_id");

                            b1.Property<Guid>("user_id")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("phone");

                            b1.HasKey("Id", "user_id")
                                .HasName("pk_contacts");

                            b1.HasIndex("user_id")
                                .IsUnique()
                                .HasDatabaseName("ix_contacts_user_id");

                            b1.ToTable("contacts", "accounts");

                            b1.WithOwner()
                                .HasForeignKey("user_id")
                                .HasConstraintName("fk_contacts_users_user_id");
                        });

                    b.OwnsOne("Domain.Users.Owns.Profile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("profile_id");

                            b1.Property<Guid>("user_id")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<string>("Avatar")
                                .HasColumnType("text")
                                .HasColumnName("avatar");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_name");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("username");

                            b1.HasKey("Id", "user_id")
                                .HasName("pk_profiles");

                            b1.HasIndex("user_id")
                                .IsUnique()
                                .HasDatabaseName("ix_profiles_user_id");

                            b1.ToTable("profiles", "accounts");

                            b1.WithOwner()
                                .HasForeignKey("user_id")
                                .HasConstraintName("fk_profiles_users_user_id");
                        });

                    b.OwnsOne("Domain.Users.Owns.Security", "Security", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("security_id");

                            b1.Property<Guid>("user_id")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<byte[]>("Password")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("password");

                            b1.Property<byte[]>("Salt")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("salt");

                            b1.HasKey("Id", "user_id")
                                .HasName("pk_security");

                            b1.HasIndex("user_id")
                                .IsUnique()
                                .HasDatabaseName("ix_security_user_id");

                            b1.ToTable("security", "accounts");

                            b1.WithOwner()
                                .HasForeignKey("user_id")
                                .HasConstraintName("fk_security_users_user_id");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Security")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
